name: Feature Request
description: Suggest an idea for the DryJets platform
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the platform is this feature for?
      options:
        - API (NestJS Backend)
        - Web Customer Portal
        - Web Merchant Portal
        - Mobile Customer App (React Native)
        - Mobile Driver App (React Native)
        - Database/Prisma
        - IoT Integration
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocking)
        - High (Important)
        - Medium (Nice to Have)
        - Low (Future Enhancement)
    validations:
      required: true

  - type: checkboxes
    id: user-type
    attributes:
      label: Target Users
      description: Who will benefit from this feature?
      options:
        - label: Customers
        - label: Merchants/Partners
        - label: Drivers
        - label: Administrators
        - label: Developers

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
